service: lambda-project-template

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: src/hello.handler

plugins:
  - serverless-mocha-plugin
  - serverless-offline

custom:
  serverless-mocha-plugin:
    functionTemplate: templates/handler-template.ejs
    testTemplate: templates/test-template.ejs